version: 2
updates:
  - package-ecosystem: "pip"
    directory: /.config/
    schedule:
      interval: "daily"
    # versioning-strategy: lockfile-only
    # allow:
    # - dependency-type: "direct"
